function osh19_output_params(params)

% Ensure the directory structure for output is created
out_path       = params.out_path;
exp_path       = fullfile(out_path, params.exp_name);
component_path = fullfile(exp_path, params.component_name);

if ~(isfolder(out_path))
    mkdir(out_path);
end
if ~(isfolder(exp_path))
    mkdir(exp_path);
end
if ~(isfolder(component_path))
    mkdir(component_path);
end

addpath(out_path);
addpath(exp_path);
addpath(component_path);

% Create output file, delete the current one if present
params_file_name = 'params.nc';
params_file = fullfile(component_path, params_file_name);
if isfile(params_file)
    delete(params_file)
end

nccreate(params_file, 'nx',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'nx', 'description', ...
    'Number of zonal grid points');
ncwriteatt(params_file, 'nx', 'units', 'N/A');
ncwrite(params_file, 'nx', params.nx);

nccreate(params_file, 'ny',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'ny', 'description', ...
    'Number of meridional grid points');
ncwriteatt(params_file, 'ny', 'units', 'N/A');
ncwrite(params_file, 'ny', params.ny);

nccreate(params_file, 'nz',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'nz', 'description', ...
    'Number of non-trivial u, v, p grid levels');
ncwriteatt(params_file, 'nz', 'units', 'N/A');
ncwrite(params_file, 'nz', params.nz);

nccreate(params_file, 'H',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'H', 'description', ...
    'Height of troposphere');
ncwriteatt(params_file, 'H', 'units', 'km');
ncwrite(params_file, 'H', params.H);

nccreate(params_file, 'P_Y',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'P_Y', 'description', ...
    'Distance from equator to channel wall');
ncwriteatt(params_file, 'P_Y', 'units', 'km');
ncwrite(params_file, 'P_Y', params.P_Y);

nccreate(params_file, 'P_E',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'P_E', 'description', ...
    'Radius of planet');
ncwriteatt(params_file, 'P_E', 'units', 'km');
ncwrite(params_file, 'P_E', params.P_E);

nccreate(params_file, 'beta',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'beta', 'description', ...
    'Meridional variation of Coriolis parameter');
ncwriteatt(params_file, 'beta', 'units', 'km^(-1) s^(-1)');
ncwrite(params_file, 'beta', params.beta);

nccreate(params_file, 'g',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'g', 'description', ...
    'Acceleration due to gravity');
ncwriteatt(params_file, 'g', 'units', 'km s^(-2)');
ncwrite(params_file, 'g', params.g);

nccreate(params_file, 'c_p',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'c_p', 'description', ...
    'Specific heat of dry air at constant pressure');
ncwriteatt(params_file, 'c_p', 'units', 'J kg^(-1) K^(-1)');
ncwrite(params_file, 'c_p', params.c_p);

nccreate(params_file, 'L_v',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'L_v', 'description', ...
    'Latent heat of vaporization');
ncwriteatt(params_file, 'L_v', 'units', 'J kg^(-1)');
ncwrite(params_file, 'L_v', params.L_v);

nccreate(params_file, 'B',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'B', 'description', ...
    'Background potential temperature vertical gradient');
ncwriteatt(params_file, 'B', 'units', 'K km^(-1)');
ncwrite(params_file, 'B', params.B);

nccreate(params_file, 'theta_0',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'theta_0', 'description', ...
    'Reference potential temperature');
ncwriteatt(params_file, 'theta_0', 'units', 'K');
ncwrite(params_file, 'theta_0', params.theta_0);

nccreate(params_file, 'tau_u',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'tau_u', 'description', ...
    'Wind damping time-scale');
ncwriteatt(params_file, 'tau_u', 'units', 's');
ncwrite(params_file, 'tau_u', params.tau_u);

nccreate(params_file, 'tau_theta',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'tau_theta', 'description', ...
    'Potential temperature damping time-scale');
ncwriteatt(params_file, 'tau_theta', 'units', 's');
ncwrite(params_file, 'tau_theta', params.tau_theta);

nccreate(params_file, 'tau_up',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'tau_up', 'description', ...
    'Moisture damping time-scale in upper-troposphere');
ncwriteatt(params_file, 'tau_up', 'units', 's');
ncwrite(params_file, 'tau_up', params.tau_up);

nccreate(params_file, 'tau_mid',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'tau_mid', 'description', ...
    'Moisture damping time-scale in mid-troposphere');
ncwriteatt(params_file, 'tau_mid', 'units', 's');
ncwrite(params_file, 'tau_mid', params.tau_mid);

nccreate(params_file, 'B_vs',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'B_vs', 'description', ...
    'Mean vertical q_bg gradient');
ncwriteatt(params_file, 'B_vs', 'units', 'kg kg^(-1) km^(-1)');
ncwrite(params_file, 'B_vs', params.B_vs);

nccreate(params_file, 'a',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'a', 'description', ...
    '1--pole-to-equator q_bg ratio');
ncwriteatt(params_file, 'a', 'units', 'N/A');
ncwrite(params_file, 'a', params.a);

nccreate(params_file, 'L_tilde',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'L_tilde', 'description', ...
    'q_bg meridional decay length scale');
ncwriteatt(params_file, 'L_tilde', 'units', 'km');
ncwrite(params_file, 'L_tilde', params.L_tilde);

nccreate(params_file, 's_tilde',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 's_tilde', 'description', ...
    'q_bg vertical decay length scale');
ncwriteatt(params_file, 's_tilde', 'units', 'km');
ncwrite(params_file, 's_tilde', params.s_tilde);

nccreate(params_file, 'D_hUp',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'D_hUp', 'description', ...
    'Horizontal q diffusion in upper-troposphere');
ncwriteatt(params_file, 'D_hUp', 'units', 'km^(2) s^(-1)');
ncwrite(params_file, 'D_hUp', params.D_hUp);

nccreate(params_file, 'D_hMid',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'D_hMid', 'description', ...
    'Horizontal q diffusion in mid-troposphere');
ncwriteatt(params_file, 'D_hMid', 'units', 'km^(2) s^(-1)');
ncwrite(params_file, 'D_hMid', params.D_hMid);

nccreate(params_file, 'D_v',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'D_v', 'description', ...
    'Vertical q diffusion');
ncwriteatt(params_file, 'D_v', 'units', 'km^(2) s^(-1)');
ncwrite(params_file, 'D_v', params.D_v);

days_to_secs = 3600*24;

nccreate(params_file, 'sim_days',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'sim_days', 'description', ...
    'Number of days in simulation');
ncwriteatt(params_file, 'sim_days', 'units', 'd');
ncwrite(params_file, 'sim_days', params.sim_days/days_to_secs);

nccreate(params_file, 'out_freq',...
    'Datatype', 'double',...
    'Format', 'netcdf4');
ncwriteatt(params_file, 'out_freq', 'description', ...
    'Number of days between output files');
ncwriteatt(params_file, 'out_freq', 'units', 'd');
ncwrite(params_file, 'out_freq', params.out_freq/days_to_secs);


end

